// <auto-generated />
using System;
using Inventarios.Server.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inventarios.Server.Migrations
{
    [DbContext(typeof(MiDbContext))]
    [Migration("20240513160033_InventarioFullDataApi")]
    partial class InventarioFullDataApi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Inventario.Server.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Sin categoria"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Deporte"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Lacteos"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Hogar"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Bebidas Gaseosas"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Frutas"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Verduras"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Carnes"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Abarrotes"
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Congelados"
                        },
                        new
                        {
                            Id = 11,
                            Nombre = "Panadería"
                        },
                        new
                        {
                            Id = 12,
                            Nombre = "Dulces y chocolates"
                        },
                        new
                        {
                            Id = 13,
                            Nombre = "Bebidas alcohólicas"
                        },
                        new
                        {
                            Id = 14,
                            Nombre = "Bebidas no alcohólicas"
                        },
                        new
                        {
                            Id = 15,
                            Nombre = "Cuidado personal"
                        },
                        new
                        {
                            Id = 16,
                            Nombre = "Electrónica"
                        },
                        new
                        {
                            Id = 17,
                            Nombre = "Ropa"
                        },
                        new
                        {
                            Id = 18,
                            Nombre = "Libros y revistas"
                        },
                        new
                        {
                            Id = 19,
                            Nombre = "Juguetes"
                        },
                        new
                        {
                            Id = 20,
                            Nombre = "Herramientas"
                        },
                        new
                        {
                            Id = 21,
                            Nombre = "Decoración"
                        },
                        new
                        {
                            Id = 22,
                            Nombre = "Automóviles"
                        },
                        new
                        {
                            Id = 23,
                            Nombre = "Jardinería"
                        },
                        new
                        {
                            Id = 24,
                            Nombre = "Mascotas"
                        },
                        new
                        {
                            Id = 25,
                            Nombre = "Instrumentos musicales"
                        });
                });

            modelBuilder.Entity("Inventarios.Server.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Celular")
                        .IsUnique();

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Celular = "3102345690",
                            Correo = "josejuandios@gmail.com",
                            Nombre = "Juan Jose"
                        },
                        new
                        {
                            Id = 2,
                            Celular = "3114315673",
                            Correo = "jumancitopues@hotmail.com",
                            Nombre = "Brayam"
                        },
                        new
                        {
                            Id = 3,
                            Celular = "3005554307",
                            Correo = "kjulio1212@outlook.com",
                            Nombre = "Kevin Julio"
                        },
                        new
                        {
                            Id = 4,
                            Celular = "3152348765",
                            Correo = "mferna@gmail.com",
                            Nombre = "María Fernanda"
                        },
                        new
                        {
                            Id = 5,
                            Celular = "3178765432",
                            Correo = "pedroperez@hotmail.com",
                            Nombre = "Pedro Pérez"
                        },
                        new
                        {
                            Id = 6,
                            Celular = "3129876543",
                            Correo = "lauramartinez@gmail.com",
                            Nombre = "Laura Martínez"
                        },
                        new
                        {
                            Id = 7,
                            Celular = "3101234567",
                            Correo = "sofiagomez@hotmail.com",
                            Nombre = "Sofía Gómez"
                        },
                        new
                        {
                            Id = 8,
                            Celular = "3009876543",
                            Correo = "carlosrodriguez@gmail.com",
                            Nombre = "Carlos Rodríguez"
                        },
                        new
                        {
                            Id = 9,
                            Celular = "3187654321",
                            Correo = "anamaria@hotmail.com",
                            Nombre = "Ana María"
                        },
                        new
                        {
                            Id = 10,
                            Celular = "3145678901",
                            Correo = "diegosanchez@gmail.com",
                            Nombre = "Diego Sánchez"
                        },
                        new
                        {
                            Id = 11,
                            Celular = "3112345678",
                            Correo = "camilalopez@hotmail.com",
                            Nombre = "Camila López"
                        },
                        new
                        {
                            Id = 12,
                            Celular = "3198765432",
                            Correo = "andresperez@gmail.com",
                            Nombre = "Andrés Pérez"
                        },
                        new
                        {
                            Id = 13,
                            Celular = "3167890123",
                            Correo = "julianatorres@hotmail.com",
                            Nombre = "Juliana Torres"
                        },
                        new
                        {
                            Id = 14,
                            Celular = "3136789012",
                            Correo = "joseluis@gmail.com",
                            Nombre = "José Luis"
                        },
                        new
                        {
                            Id = 15,
                            Celular = "3108901234",
                            Correo = "danielaramirez@hotmail.com",
                            Nombre = "Daniela Ramírez"
                        },
                        new
                        {
                            Id = 16,
                            Celular = "3174567890",
                            Correo = "gabrielgutierrez@gmail.com",
                            Nombre = "Gabriel Gutiérrez"
                        },
                        new
                        {
                            Id = 17,
                            Celular = "3006789012",
                            Correo = "valentinadiaz@hotmail.com",
                            Nombre = "Valentina Díaz"
                        },
                        new
                        {
                            Id = 18,
                            Celular = "3190123456",
                            Correo = "davidgarcia@gmail.com",
                            Nombre = "David García"
                        },
                        new
                        {
                            Id = 19,
                            Celular = "3124567890",
                            Correo = "marianasilva@hotmail.com",
                            Nombre = "Mariana Silva"
                        },
                        new
                        {
                            Id = 20,
                            Celular = "3147890123",
                            Correo = "alejandrovargas@gmail.com",
                            Nombre = "Alejandro Vargas"
                        });
                });

            modelBuilder.Entity("Inventarios.Server.Models.Entrada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExistenciaActual")
                        .HasColumnType("int");

                    b.Property<int>("ExistenciaInicial")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEntrada")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<string>("Nota")
                        .HasMaxLength(999)
                        .HasColumnType("nvarchar(999)");

                    b.Property<decimal>("PrecioCompra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdProveedor");

                    b.ToTable("Entradas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = "Activo",
                            ExistenciaActual = 50,
                            ExistenciaInicial = 50,
                            FechaEntrada = new DateTime(2024, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 6,
                            IdProducto = 11,
                            IdProveedor = 5,
                            Nota = "",
                            PrecioCompra = 20000m,
                            PrecioVenta = 80000m
                        },
                        new
                        {
                            Id = 2,
                            Estado = "Activo",
                            ExistenciaActual = 150,
                            ExistenciaInicial = 150,
                            FechaEntrada = new DateTime(2024, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 8,
                            IdProducto = 20,
                            IdProveedor = 7,
                            Nota = "",
                            PrecioCompra = 90000m,
                            PrecioVenta = 200000m
                        },
                        new
                        {
                            Id = 3,
                            Estado = "Activo",
                            ExistenciaActual = 50,
                            ExistenciaInicial = 50,
                            FechaEntrada = new DateTime(2024, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 10,
                            IdProducto = 23,
                            IdProveedor = 9,
                            Nota = "",
                            PrecioCompra = 10000m,
                            PrecioVenta = 35000m
                        },
                        new
                        {
                            Id = 4,
                            Estado = "Activo",
                            ExistenciaActual = 200,
                            ExistenciaInicial = 200,
                            FechaEntrada = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 10,
                            IdProducto = 26,
                            IdProveedor = 9,
                            Nota = "",
                            PrecioCompra = 4000000m,
                            PrecioVenta = 4700000m
                        },
                        new
                        {
                            Id = 5,
                            Estado = "Activo",
                            ExistenciaActual = 50,
                            ExistenciaInicial = 50,
                            FechaEntrada = new DateTime(2024, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 11,
                            IdProducto = 29,
                            IdProveedor = 10,
                            Nota = "",
                            PrecioCompra = 35000m,
                            PrecioVenta = 80000m
                        },
                        new
                        {
                            Id = 6,
                            Estado = "Activo",
                            ExistenciaActual = 400,
                            ExistenciaInicial = 400,
                            FechaEntrada = new DateTime(2024, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 12,
                            IdProducto = 31,
                            IdProveedor = 11,
                            Nota = "",
                            PrecioCompra = 58000m,
                            PrecioVenta = 80000m
                        },
                        new
                        {
                            Id = 7,
                            Estado = "Activo",
                            ExistenciaActual = 100,
                            ExistenciaInicial = 100,
                            FechaEntrada = new DateTime(2024, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 12,
                            IdProducto = 34,
                            IdProveedor = 11,
                            Nota = "",
                            PrecioCompra = 45000m,
                            PrecioVenta = 80000m
                        },
                        new
                        {
                            Id = 8,
                            Estado = "Activo",
                            ExistenciaActual = 300,
                            ExistenciaInicial = 300,
                            FechaEntrada = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 12,
                            IdProducto = 35,
                            IdProveedor = 11,
                            Nota = "",
                            PrecioCompra = 65000m,
                            PrecioVenta = 215680m
                        },
                        new
                        {
                            Id = 9,
                            Estado = "Activo",
                            ExistenciaActual = 70,
                            ExistenciaInicial = 70,
                            FechaEntrada = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 13,
                            IdProducto = 42,
                            IdProveedor = 12,
                            Nota = "",
                            PrecioCompra = 60999m,
                            PrecioVenta = 120000m
                        },
                        new
                        {
                            Id = 10,
                            Estado = "Activo",
                            ExistenciaActual = 90,
                            ExistenciaInicial = 90,
                            FechaEntrada = new DateTime(2024, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 14,
                            IdProducto = 40,
                            IdProveedor = 13,
                            Nota = "",
                            PrecioCompra = 700000m,
                            PrecioVenta = 8000000m
                        },
                        new
                        {
                            Id = 11,
                            Estado = "Activo",
                            ExistenciaActual = 200,
                            ExistenciaInicial = 200,
                            FechaEntrada = new DateTime(2024, 2, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 15,
                            IdProducto = 45,
                            IdProveedor = 14,
                            Nota = "",
                            PrecioCompra = 5000000m,
                            PrecioVenta = 8000000m
                        },
                        new
                        {
                            Id = 12,
                            Estado = "Activo",
                            ExistenciaActual = 135,
                            ExistenciaInicial = 135,
                            FechaEntrada = new DateTime(2024, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 15,
                            IdProducto = 44,
                            IdProveedor = 14,
                            Nota = "",
                            PrecioCompra = 30000m,
                            PrecioVenta = 40000m
                        },
                        new
                        {
                            Id = 13,
                            Estado = "Activo",
                            ExistenciaActual = 80,
                            ExistenciaInicial = 80,
                            FechaEntrada = new DateTime(2024, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 16,
                            IdProducto = 47,
                            IdProveedor = 15,
                            Nota = "",
                            PrecioCompra = 400000m,
                            PrecioVenta = 535000m
                        },
                        new
                        {
                            Id = 14,
                            Estado = "Activo",
                            ExistenciaActual = 100,
                            ExistenciaInicial = 100,
                            FechaEntrada = new DateTime(2024, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 16,
                            IdProducto = 48,
                            IdProveedor = 15,
                            Nota = "",
                            PrecioCompra = 32400m,
                            PrecioVenta = 53490m
                        },
                        new
                        {
                            Id = 15,
                            Estado = "Activo",
                            ExistenciaActual = 50,
                            ExistenciaInicial = 50,
                            FechaEntrada = new DateTime(2024, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 16,
                            IdProducto = 49,
                            IdProveedor = 15,
                            Nota = "",
                            PrecioCompra = 35690m,
                            PrecioVenta = 109000m
                        },
                        new
                        {
                            Id = 16,
                            Estado = "Activo",
                            ExistenciaActual = 35,
                            ExistenciaInicial = 35,
                            FechaEntrada = new DateTime(2024, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 16,
                            IdProducto = 50,
                            IdProveedor = 15,
                            Nota = "",
                            PrecioCompra = 22000m,
                            PrecioVenta = 40000m
                        },
                        new
                        {
                            Id = 17,
                            Estado = "Activo",
                            ExistenciaActual = 300,
                            ExistenciaInicial = 300,
                            FechaEntrada = new DateTime(2024, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 16,
                            IdProducto = 53,
                            IdProveedor = 15,
                            Nota = "",
                            PrecioCompra = 58000m,
                            PrecioVenta = 98000m
                        },
                        new
                        {
                            Id = 18,
                            Estado = "Activo",
                            ExistenciaActual = 50,
                            ExistenciaInicial = 50,
                            FechaEntrada = new DateTime(2024, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 16,
                            IdProducto = 55,
                            IdProveedor = 15,
                            Nota = "",
                            PrecioCompra = 13000m,
                            PrecioVenta = 80000m
                        },
                        new
                        {
                            Id = 19,
                            Estado = "Activo",
                            ExistenciaActual = 50,
                            ExistenciaInicial = 50,
                            FechaEntrada = new DateTime(2024, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 17,
                            IdProducto = 59,
                            IdProveedor = 16,
                            Nota = "",
                            PrecioCompra = 11000m,
                            PrecioVenta = 18000m
                        },
                        new
                        {
                            Id = 20,
                            Estado = "Activo",
                            ExistenciaActual = 40,
                            ExistenciaInicial = 40,
                            FechaEntrada = new DateTime(2024, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 17,
                            IdProducto = 61,
                            IdProveedor = 16,
                            Nota = "",
                            PrecioCompra = 42300m,
                            PrecioVenta = 67800m
                        },
                        new
                        {
                            Id = 21,
                            Estado = "Activo",
                            ExistenciaActual = 38,
                            ExistenciaInicial = 38,
                            FechaEntrada = new DateTime(2024, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 18,
                            IdProducto = 63,
                            IdProveedor = 17,
                            Nota = "",
                            PrecioCompra = 2000000m,
                            PrecioVenta = 3500000m
                        },
                        new
                        {
                            Id = 22,
                            Estado = "Activo",
                            ExistenciaActual = 200,
                            ExistenciaInicial = 200,
                            FechaEntrada = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 19,
                            IdProducto = 66,
                            IdProveedor = 18,
                            Nota = "",
                            PrecioCompra = 1200000m,
                            PrecioVenta = 2000000m
                        },
                        new
                        {
                            Id = 23,
                            Estado = "Activo",
                            ExistenciaActual = 50,
                            ExistenciaInicial = 50,
                            FechaEntrada = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 19,
                            IdProducto = 67,
                            IdProveedor = 18,
                            Nota = "",
                            PrecioCompra = 500000m,
                            PrecioVenta = 800000m
                        },
                        new
                        {
                            Id = 24,
                            Estado = "Activo",
                            ExistenciaActual = 70,
                            ExistenciaInicial = 70,
                            FechaEntrada = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 20,
                            IdProducto = 73,
                            IdProveedor = 19,
                            Nota = "",
                            PrecioCompra = 250000m,
                            PrecioVenta = 800000m
                        },
                        new
                        {
                            Id = 25,
                            Estado = "Activo",
                            ExistenciaActual = 200,
                            ExistenciaInicial = 200,
                            FechaEntrada = new DateTime(2024, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 21,
                            IdProducto = 75,
                            IdProveedor = 20,
                            Nota = "",
                            PrecioCompra = 1200000m,
                            PrecioVenta = 2000000m
                        },
                        new
                        {
                            Id = 26,
                            Estado = "Activo",
                            ExistenciaActual = 50,
                            ExistenciaInicial = 50,
                            FechaEntrada = new DateTime(2024, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 21,
                            IdProducto = 77,
                            IdProveedor = 20,
                            Nota = "",
                            PrecioCompra = 500000m,
                            PrecioVenta = 800000m
                        },
                        new
                        {
                            Id = 27,
                            Estado = "Activo",
                            ExistenciaActual = 70,
                            ExistenciaInicial = 70,
                            FechaEntrada = new DateTime(2024, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 21,
                            IdProducto = 78,
                            IdProveedor = 20,
                            Nota = "",
                            PrecioCompra = 250000m,
                            PrecioVenta = 800000m
                        },
                        new
                        {
                            Id = 28,
                            Estado = "Activo",
                            ExistenciaActual = 200,
                            ExistenciaInicial = 200,
                            FechaEntrada = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 22,
                            IdProducto = 80,
                            IdProveedor = 21,
                            Nota = "",
                            PrecioCompra = 1200000m,
                            PrecioVenta = 2000000m
                        },
                        new
                        {
                            Id = 29,
                            Estado = "Activo",
                            ExistenciaActual = 50,
                            ExistenciaInicial = 50,
                            FechaEntrada = new DateTime(2024, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 23,
                            IdProducto = 81,
                            IdProveedor = 22,
                            Nota = "",
                            PrecioCompra = 500000m,
                            PrecioVenta = 800000m
                        },
                        new
                        {
                            Id = 30,
                            Estado = "Activo",
                            ExistenciaActual = 70,
                            ExistenciaInicial = 70,
                            FechaEntrada = new DateTime(2024, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 24,
                            IdProducto = 84,
                            IdProveedor = 23,
                            Nota = "",
                            PrecioCompra = 250000m,
                            PrecioVenta = 800000m
                        },
                        new
                        {
                            Id = 31,
                            Estado = "Activo",
                            ExistenciaActual = 50,
                            ExistenciaInicial = 50,
                            FechaEntrada = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 25,
                            IdProducto = 87,
                            IdProveedor = 24,
                            Nota = "",
                            PrecioCompra = 500000m,
                            PrecioVenta = 800000m
                        },
                        new
                        {
                            Id = 32,
                            Estado = "Activo",
                            ExistenciaActual = 70,
                            ExistenciaInicial = 70,
                            FechaEntrada = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 25,
                            IdProducto = 88,
                            IdProveedor = 24,
                            Nota = "",
                            PrecioCompra = 250000m,
                            PrecioVenta = 800000m
                        },
                        new
                        {
                            Id = 33,
                            Estado = "Activo",
                            ExistenciaActual = 200,
                            ExistenciaInicial = 200,
                            FechaEntrada = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 25,
                            IdProducto = 89,
                            IdProveedor = 24,
                            Nota = "",
                            PrecioCompra = 1200000m,
                            PrecioVenta = 2000000m
                        },
                        new
                        {
                            Id = 34,
                            Estado = "Activo",
                            ExistenciaActual = 50,
                            ExistenciaInicial = 50,
                            FechaEntrada = new DateTime(2024, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 25,
                            IdProducto = 85,
                            IdProveedor = 24,
                            Nota = "",
                            PrecioCompra = 500000m,
                            PrecioVenta = 800000m
                        },
                        new
                        {
                            Id = 35,
                            Estado = "Activo",
                            ExistenciaActual = 70,
                            ExistenciaInicial = 70,
                            FechaEntrada = new DateTime(2024, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 5,
                            IdProducto = 5,
                            IdProveedor = 4,
                            Nota = "",
                            PrecioCompra = 250000m,
                            PrecioVenta = 800000m
                        });
                });

            modelBuilder.Entity("Inventarios.Server.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(999)
                        .HasColumnType("nvarchar(999)");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoria");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Leche sin conservantes de 250l",
                            IdCategoria = 3,
                            Nombre = "Leche deslactosada"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Perfectas para jugar tennis, duracion de hasta 2 años sino te regresamos tu dinero",
                            IdCategoria = 2,
                            Nombre = "Pelotas de tennis"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Yogurt sin azucar de 280ml",
                            IdCategoria = 3,
                            Nombre = "Yogurt griego"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "La mas alta calidad exportada de japon, contiene todas las vitaminas que tu cuerpo necesita de 500ml",
                            IdCategoria = 3,
                            Nombre = "Leche premium"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "presentacion de 175l",
                            IdCategoria = 5,
                            Nombre = "Gaseosa litron postobon"
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Perfecto para tu sala de 5 puestos",
                            IdCategoria = 4,
                            Nombre = "Mueble familiar"
                        },
                        new
                        {
                            Id = 7,
                            Descripcion = "Presentacion en lata de 180ml",
                            IdCategoria = 5,
                            Nombre = "Gaseosa en lata"
                        },
                        new
                        {
                            Id = 8,
                            Descripcion = "Balon del FPC",
                            IdCategoria = 2,
                            Nombre = "Balon de futbol profesional"
                        },
                        new
                        {
                            Id = 9,
                            Descripcion = "Cuaderno norma de 100 hojas",
                            IdCategoria = 1,
                            Nombre = "Cuaderno cuadriculado 100 hojas"
                        },
                        new
                        {
                            Id = 10,
                            Descripcion = "Huevos 100% de campo",
                            IdCategoria = 1,
                            Nombre = "huevos criollos"
                        },
                        new
                        {
                            Id = 11,
                            Descripcion = "Manzanas frescas y jugosas de variedad verde",
                            IdCategoria = 6,
                            Nombre = "Manzanas verdes"
                        },
                        new
                        {
                            Id = 12,
                            Descripcion = "Piñas maduras y dulces de origen tropical",
                            IdCategoria = 6,
                            Nombre = "Piñas tropicales"
                        },
                        new
                        {
                            Id = 13,
                            Descripcion = "Naranjas valencianas de alta calidad y sabor intenso",
                            IdCategoria = 6,
                            Nombre = "Naranjas Valencia"
                        },
                        new
                        {
                            Id = 14,
                            Descripcion = "Plátanos maduros de la variedad dominicana",
                            IdCategoria = 6,
                            Nombre = "Plátanos dominicos"
                        },
                        new
                        {
                            Id = 15,
                            Descripcion = "Tomate fresco de la mejor calidad",
                            IdCategoria = 7,
                            Nombre = "Tomate"
                        },
                        new
                        {
                            Id = 16,
                            Descripcion = "Lechuga fresca y crujiente",
                            IdCategoria = 7,
                            Nombre = "Lechuga"
                        },
                        new
                        {
                            Id = 17,
                            Descripcion = "Pepino verde y fresco",
                            IdCategoria = 7,
                            Nombre = "Pepino"
                        },
                        new
                        {
                            Id = 18,
                            Descripcion = "Filete de res de alta calidad",
                            IdCategoria = 8,
                            Nombre = "Filete de Res"
                        },
                        new
                        {
                            Id = 19,
                            Descripcion = "Pechuga de pollo fresca y jugosa",
                            IdCategoria = 8,
                            Nombre = "Pechuga de Pollo"
                        },
                        new
                        {
                            Id = 20,
                            Descripcion = "Chuleta de cerdo fresca y tierna",
                            IdCategoria = 8,
                            Nombre = "Chuleta de Cerdo"
                        },
                        new
                        {
                            Id = 21,
                            Descripcion = "Arroz blanco de grano largo",
                            IdCategoria = 9,
                            Nombre = "Arroz"
                        },
                        new
                        {
                            Id = 22,
                            Descripcion = "Filete de salmón congelado al vacío",
                            IdCategoria = 10,
                            Nombre = "Filete de salmón congelado"
                        },
                        new
                        {
                            Id = 23,
                            Descripcion = "Pizza congelada de pepperoni lista para hornear",
                            IdCategoria = 10,
                            Nombre = "Pizza congelada de pepperoni"
                        },
                        new
                        {
                            Id = 24,
                            Descripcion = "Helado de vainilla en envase de 1 litro",
                            IdCategoria = 10,
                            Nombre = "Helado de vainilla"
                        },
                        new
                        {
                            Id = 25,
                            Descripcion = "Croquetas de pollo congeladas, caja de 500g",
                            IdCategoria = 10,
                            Nombre = "Croquetas de pollo"
                        },
                        new
                        {
                            Id = 26,
                            Descripcion = "Papas fritas congeladas, bolsa de 1kg",
                            IdCategoria = 10,
                            Nombre = "Papas fritas congeladas"
                        },
                        new
                        {
                            Id = 27,
                            Descripcion = "Mezcla de vegetales congelados, bolsa de 500g",
                            IdCategoria = 10,
                            Nombre = "Vegetales mixtos congelados"
                        },
                        new
                        {
                            Id = 28,
                            Descripcion = "Pan blanco fresco, barra de 500g",
                            IdCategoria = 11,
                            Nombre = "Pan blanco"
                        },
                        new
                        {
                            Id = 29,
                            Descripcion = "Croissant de mantequilla recién horneado",
                            IdCategoria = 11,
                            Nombre = "Croissant de mantequilla"
                        },
                        new
                        {
                            Id = 30,
                            Descripcion = "Tableta de chocolate con leche",
                            IdCategoria = 12,
                            Nombre = "Chocolate con leche"
                        },
                        new
                        {
                            Id = 31,
                            Descripcion = "Tableta de chocolate amargo, 70% cacao",
                            IdCategoria = 12,
                            Nombre = "Chocolate amargo"
                        },
                        new
                        {
                            Id = 32,
                            Descripcion = "Bolsa de gomitas de frutas surtidas",
                            IdCategoria = 12,
                            Nombre = "Gomitas de frutas"
                        },
                        new
                        {
                            Id = 33,
                            Descripcion = "Bolsa de malvaviscos cubiertos de azúcar",
                            IdCategoria = 12,
                            Nombre = "Malvaviscos"
                        },
                        new
                        {
                            Id = 34,
                            Descripcion = "Bolsa de caramelos surtidos",
                            IdCategoria = 12,
                            Nombre = "Caramelos surtidos"
                        },
                        new
                        {
                            Id = 35,
                            Descripcion = "Paquete de chicles de menta, sin azúcar",
                            IdCategoria = 12,
                            Nombre = "Chicle de menta"
                        },
                        new
                        {
                            Id = 36,
                            Descripcion = "Caja de bombones de chocolate surtidos",
                            IdCategoria = 12,
                            Nombre = "Bombones de chocolate"
                        },
                        new
                        {
                            Id = 37,
                            Descripcion = "Paquete de alfajores de dulce de leche, cubiertos de chocolate",
                            IdCategoria = 12,
                            Nombre = "Alfajores de dulce de leche"
                        },
                        new
                        {
                            Id = 38,
                            Descripcion = "Botella de agua mineral sin gas",
                            IdCategoria = 14,
                            Nombre = "Agua mineral"
                        },
                        new
                        {
                            Id = 39,
                            Descripcion = "Botella de refresco de cola de 2 litros",
                            IdCategoria = 14,
                            Nombre = "Refresco de cola"
                        },
                        new
                        {
                            Id = 40,
                            Descripcion = "Envase de jugo de naranja natural de 1 litro",
                            IdCategoria = 14,
                            Nombre = "Jugo de naranja"
                        },
                        new
                        {
                            Id = 41,
                            Descripcion = "Botella de vino tinto reserva de 750 ml",
                            IdCategoria = 13,
                            Nombre = "Vino tinto reserva"
                        },
                        new
                        {
                            Id = 42,
                            Descripcion = "Six-pack de cerveza artesanal India Pale Ale (IPA)",
                            IdCategoria = 13,
                            Nombre = "Cerveza artesanal IPA"
                        },
                        new
                        {
                            Id = 43,
                            Descripcion = "Shampoo para fortalecer el cabello, envase de 400 ml",
                            IdCategoria = 15,
                            Nombre = "Shampoo fortificante"
                        },
                        new
                        {
                            Id = 44,
                            Descripcion = "Crema facial hidratante con ácido hialurónico, envase de 50 ml",
                            IdCategoria = 15,
                            Nombre = "Crema hidratante facial"
                        },
                        new
                        {
                            Id = 45,
                            Descripcion = "Desodorante en barra para hombre, sin alcohol, envase de 50 g",
                            IdCategoria = 15,
                            Nombre = "Desodorante en barra"
                        },
                        new
                        {
                            Id = 46,
                            Descripcion = "Hilo dental con menta, 50 metros",
                            IdCategoria = 15,
                            Nombre = "Dental floss"
                        },
                        new
                        {
                            Id = 47,
                            Descripcion = "Auriculares Bluetooth con cancelación de ruido, color negro",
                            IdCategoria = 16,
                            Nombre = "Auriculares inalámbricos"
                        },
                        new
                        {
                            Id = 48,
                            Descripcion = "Reloj inteligente resistente al agua con GPS integrado, color rojo",
                            IdCategoria = 16,
                            Nombre = "Smartwatch deportivo"
                        },
                        new
                        {
                            Id = 49,
                            Descripcion = "Base de carga inalámbrica rápida para teléfonos compatibles, color blanco",
                            IdCategoria = 16,
                            Nombre = "Cargador inalámbrico"
                        },
                        new
                        {
                            Id = 50,
                            Descripcion = "Power bank de 20000 mAh con puerto USB-C y USB-A, color gris",
                            IdCategoria = 16,
                            Nombre = "Batería externa"
                        },
                        new
                        {
                            Id = 51,
                            Descripcion = "Altavoz portátil con sonido estéreo de alta definición, color azul",
                            IdCategoria = 16,
                            Nombre = "Altavoz Bluetooth"
                        },
                        new
                        {
                            Id = 52,
                            Descripcion = "Cámara IP para interiores con visión nocturna y detección de movimiento, color blanco",
                            IdCategoria = 16,
                            Nombre = "Cámara de seguridad Wi-Fi"
                        },
                        new
                        {
                            Id = 53,
                            Descripcion = "Teclado retroiluminado con switches mecánicos y anti-ghosting, color negro",
                            IdCategoria = 16,
                            Nombre = "Teclado mecánico gaming"
                        },
                        new
                        {
                            Id = 54,
                            Descripcion = "Mouse ergonómico con sensor óptico de alta precisión, color gris",
                            IdCategoria = 16,
                            Nombre = "Mouse óptico"
                        },
                        new
                        {
                            Id = 55,
                            Descripcion = "Router inalámbrico de última generación con velocidad de hasta 6000 Mbps, color negro",
                            IdCategoria = 16,
                            Nombre = "Router Wi-Fi 6"
                        },
                        new
                        {
                            Id = 56,
                            Descripcion = "Tableta digitalizadora con lápiz sensible a la presión, ideal para diseño gráfico, color blanco",
                            IdCategoria = 16,
                            Nombre = "Tableta gráfica"
                        },
                        new
                        {
                            Id = 57,
                            Descripcion = "Bombilla LED inteligente controlable por voz y aplicación móvil, color blanco cálido",
                            IdCategoria = 16,
                            Nombre = "Lámpara inteligente"
                        },
                        new
                        {
                            Id = 58,
                            Descripcion = "Camisa de algodón con cuello clásico y botones frontales, color blanco",
                            IdCategoria = 17,
                            Nombre = "Camisa de vestir"
                        },
                        new
                        {
                            Id = 59,
                            Descripcion = "Jeans de corte recto y diseño clásico, color azul índigo",
                            IdCategoria = 17,
                            Nombre = "Pantalones vaqueros"
                        },
                        new
                        {
                            Id = 60,
                            Descripcion = "Vestido largo de satén con escote en V y detalle de encaje, color negro",
                            IdCategoria = 17,
                            Nombre = "Vestido de fiesta"
                        },
                        new
                        {
                            Id = 61,
                            Descripcion = "Tenis para correr con amortiguación y suela de goma, color gris y rosa",
                            IdCategoria = 17,
                            Nombre = "Zapatillas deportivas"
                        },
                        new
                        {
                            Id = 62,
                            Descripcion = "Bufanda suave y abrigada tejida a mano, color gris jaspeado",
                            IdCategoria = 17,
                            Nombre = "Bufanda de lana"
                        },
                        new
                        {
                            Id = 63,
                            Descripcion = "Colección de recetas auténticas de diversas regiones del mundo",
                            IdCategoria = 18,
                            Nombre = "Libro de cocina: Recetas tradicionales"
                        },
                        new
                        {
                            Id = 64,
                            Descripcion = "Edición mensual con los estilos más actuales y consejos de moda",
                            IdCategoria = 18,
                            Nombre = "Revista de moda: Últimas tendencias"
                        },
                        new
                        {
                            Id = 65,
                            Descripcion = "Muñeca de 30 cm con ropa intercambiable y accesorios",
                            IdCategoria = 19,
                            Nombre = "Muñeca articulada"
                        },
                        new
                        {
                            Id = 66,
                            Descripcion = "Set de carreras con pistas, coches y accesorios para montar",
                            IdCategoria = 19,
                            Nombre = "Circuito de carreras"
                        },
                        new
                        {
                            Id = 67,
                            Descripcion = "Rompecabezas de paisajes naturales para armar en familia",
                            IdCategoria = 19,
                            Nombre = "Rompecabezas de 1000 piezas"
                        },
                        new
                        {
                            Id = 68,
                            Descripcion = "Set de 200 bloques de colores para construir y crear",
                            IdCategoria = 19,
                            Nombre = "Set de bloques de construcción"
                        },
                        new
                        {
                            Id = 69,
                            Descripcion = "Peluche suave de 1 metro de altura para abrazar",
                            IdCategoria = 19,
                            Nombre = "Peluche gigante de oso"
                        },
                        new
                        {
                            Id = 70,
                            Descripcion = "Set con materiales para crear manualidades y proyectos artísticos",
                            IdCategoria = 19,
                            Nombre = "Kit de manualidades para niños"
                        },
                        new
                        {
                            Id = 71,
                            Descripcion = "Juego de mesa interactivo para explorar la selva y superar desafíos",
                            IdCategoria = 19,
                            Nombre = "Juego de mesa: Aventuras en la selva"
                        },
                        new
                        {
                            Id = 72,
                            Descripcion = "Set de 6 destornilladores de diferentes tamaños y puntas",
                            IdCategoria = 20,
                            Nombre = "Juego de destornilladores"
                        },
                        new
                        {
                            Id = 73,
                            Descripcion = "Taladro con batería recargable, ideal para trabajos domésticos",
                            IdCategoria = 20,
                            Nombre = "Taladro eléctrico inalámbrico"
                        },
                        new
                        {
                            Id = 74,
                            Descripcion = "Caja resistente con compartimentos y ruedas para transportar herramientas",
                            IdCategoria = 20,
                            Nombre = "Caja de herramientas con ruedas"
                        },
                        new
                        {
                            Id = 75,
                            Descripcion = "Cuadro decorativo con diseño abstracto y marco de madera",
                            IdCategoria = 21,
                            Nombre = "Cuadro abstracto moderno"
                        },
                        new
                        {
                            Id = 76,
                            Descripcion = "Set de 4 cojines con diferentes diseños y colores para sofá o cama",
                            IdCategoria = 21,
                            Nombre = "Cojines decorativos"
                        },
                        new
                        {
                            Id = 77,
                            Descripcion = "Jarrón decorativo de cerámica con diseño elegante para flores",
                            IdCategoria = 21,
                            Nombre = "Jarrón de cerámica"
                        },
                        new
                        {
                            Id = 78,
                            Descripcion = "Espejo de pared con marco de metal negro, ideal para entrada o sala",
                            IdCategoria = 21,
                            Nombre = "Espejo de pared rectangular"
                        },
                        new
                        {
                            Id = 79,
                            Descripcion = "Llantas de alta performance para vehículos deportivos",
                            IdCategoria = 22,
                            Nombre = "Llantas deportivas"
                        },
                        new
                        {
                            Id = 80,
                            Descripcion = "Kit completo de luces LED para mejorar la iluminación del vehículo",
                            IdCategoria = 22,
                            Nombre = "Kit de luces LED para automóviles"
                        },
                        new
                        {
                            Id = 81,
                            Descripcion = "Podadora eléctrica para cortar el césped de jardines pequeños y medianos",
                            IdCategoria = 23,
                            Nombre = "Podadora de césped eléctrica"
                        },
                        new
                        {
                            Id = 82,
                            Descripcion = "Collar resistente y ajustable para perros de todos los tamaños",
                            IdCategoria = 24,
                            Nombre = "Collar ajustable para perros"
                        },
                        new
                        {
                            Id = 83,
                            Descripcion = "Juguete interactivo para gatos con plumas y sonidos que estimulan su instinto de caza",
                            IdCategoria = 24,
                            Nombre = "Juguete para gatos con plumas"
                        },
                        new
                        {
                            Id = 84,
                            Descripcion = "Comedero automático programable para perros y gatos que dispensa comida en horarios predefinidos",
                            IdCategoria = 24,
                            Nombre = "Comedero automático para mascotas"
                        },
                        new
                        {
                            Id = 85,
                            Descripcion = "Guitarra acústica de calidad con cuerdas de nylon para principiantes",
                            IdCategoria = 25,
                            Nombre = "Guitarra acústica"
                        },
                        new
                        {
                            Id = 86,
                            Descripcion = "Teclado electrónico de 61 teclas con múltiples funciones y sonidos",
                            IdCategoria = 25,
                            Nombre = "Teclado electrónico"
                        },
                        new
                        {
                            Id = 87,
                            Descripcion = "Batería infantil de tamaño compacto con todo lo necesario para empezar a tocar",
                            IdCategoria = 25,
                            Nombre = "Batería completa para niños"
                        },
                        new
                        {
                            Id = 88,
                            Descripcion = "Violín de alta calidad hecho a mano con madera de abeto y arce",
                            IdCategoria = 25,
                            Nombre = "Violín profesional"
                        },
                        new
                        {
                            Id = 89,
                            Descripcion = "Micrófono de condensador con soporte y filtro anti-pop para grabaciones profesionales",
                            IdCategoria = 25,
                            Nombre = "Micrófono de condensador"
                        },
                        new
                        {
                            Id = 90,
                            Descripcion = "Piano digital portátil con teclado contrapesado y múltiples sonidos de alta calidad",
                            IdCategoria = 25,
                            Nombre = "Piano digital de escenario"
                        });
                });

            modelBuilder.Entity("Inventarios.Server.Models.ProductoSalida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<int>("IdEntrada")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<int>("IdSalida")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorDescuento")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdEntrada");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdSalida");

                    b.ToTable("ProductoSalidas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 5,
                            Descuento = 0m,
                            IdCategoria = 3,
                            IdEntrada = 1,
                            IdProducto = 3,
                            IdSalida = 1,
                            Precio = 8000m,
                            Total = 40000m,
                            ValorDescuento = 0m
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 100,
                            Descuento = 10m,
                            IdCategoria = 5,
                            IdEntrada = 2,
                            IdProducto = 7,
                            IdSalida = 1,
                            Precio = 2600m,
                            Total = 234000m,
                            ValorDescuento = 26000m
                        },
                        new
                        {
                            Id = 3,
                            Cantidad = 20,
                            Descuento = 5m,
                            IdCategoria = 2,
                            IdEntrada = 3,
                            IdProducto = 8,
                            IdSalida = 2,
                            Precio = 190000m,
                            Total = 3610000m,
                            ValorDescuento = 190000m
                        },
                        new
                        {
                            Id = 4,
                            Cantidad = 15,
                            Descuento = 5m,
                            IdCategoria = 3,
                            IdEntrada = 1,
                            IdProducto = 3,
                            IdSalida = 3,
                            Precio = 8000m,
                            Total = 114000m,
                            ValorDescuento = 6000m
                        },
                        new
                        {
                            Id = 5,
                            Cantidad = 20,
                            Descuento = 2m,
                            IdCategoria = 5,
                            IdEntrada = 2,
                            IdProducto = 7,
                            IdSalida = 3,
                            Precio = 2600m,
                            Total = 50960m,
                            ValorDescuento = 1040m
                        });
                });

            modelBuilder.Entity("Inventarios.Server.Models.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Celular")
                        .IsUnique();

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("Proveedors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Celular = "3187779090",
                            Correo = "adidascolombia@gmail.com",
                            Nombre = "Adidas"
                        },
                        new
                        {
                            Id = 2,
                            Celular = "3145623143",
                            Correo = "colontacol@hotmail.com",
                            Nombre = "Colanta"
                        },
                        new
                        {
                            Id = 3,
                            Celular = "3005554307",
                            Correo = "mueblesjamar@gmail.com",
                            Nombre = "Jamar"
                        },
                        new
                        {
                            Id = 4,
                            Celular = "3005567889",
                            Correo = "postoboncol@gmail.com",
                            Nombre = "Postobon"
                        },
                        new
                        {
                            Id = 5,
                            Celular = "3156789012",
                            Correo = "frutastropicales@hotmail.com",
                            Nombre = "Frutas Tropicales"
                        },
                        new
                        {
                            Id = 6,
                            Celular = "3159876543",
                            Correo = "Donve@gmail.com",
                            Nombre = "Verduras Don Colombia"
                        },
                        new
                        {
                            Id = 7,
                            Celular = "3128901234",
                            Correo = "donjuancarniceria@gmail.com",
                            Nombre = "Carnicería Don Juan"
                        },
                        new
                        {
                            Id = 8,
                            Celular = "3188765432",
                            Correo = "abarro@hotmail.com",
                            Nombre = "Super Abarrotes La Familia"
                        },
                        new
                        {
                            Id = 9,
                            Celular = "3112345678",
                            Correo = "elvene12345@hotmail.com",
                            Nombre = "Congelados el vene"
                        },
                        new
                        {
                            Id = 10,
                            Celular = "3198765432",
                            Correo = "bimbocolombia@gmail.com",
                            Nombre = "Bimbo"
                        },
                        new
                        {
                            Id = 11,
                            Celular = "3105678901",
                            Correo = "colombina@hotmail.com",
                            Nombre = "Colombina"
                        },
                        new
                        {
                            Id = 12,
                            Celular = "3146789012",
                            Correo = "clubCo@gmail.com",
                            Nombre = "Club Colombia"
                        },
                        new
                        {
                            Id = 13,
                            Celular = "3177890123",
                            Correo = "Brisa@hotmail.com",
                            Nombre = "Brisa"
                        },
                        new
                        {
                            Id = 14,
                            Celular = "3128901200",
                            Correo = "gille@gmail.com",
                            Nombre = "Gillette"
                        },
                        new
                        {
                            Id = 15,
                            Celular = "3189012345",
                            Correo = "IntelCo@gmail.com",
                            Nombre = "Intel Co."
                        },
                        new
                        {
                            Id = 16,
                            Celular = "3150123456",
                            Correo = "NikeCol@hotmail.com",
                            Nombre = "Nike"
                        },
                        new
                        {
                            Id = 17,
                            Celular = "3191234567",
                            Correo = "Elrincon@gmail.com",
                            Nombre = "Rincon del vago"
                        },
                        new
                        {
                            Id = 18,
                            Celular = "3102345678",
                            Correo = "MatelsaJuguetes@gmail.com",
                            Nombre = "Matelsa"
                        },
                        new
                        {
                            Id = 19,
                            Celular = "3153456789",
                            Correo = "IngcoCO@hotmail.com",
                            Nombre = "IngCo"
                        },
                        new
                        {
                            Id = 20,
                            Celular = "3124567890",
                            Correo = "brissaa@gmail.com",
                            Nombre = "Brissa"
                        },
                        new
                        {
                            Id = 21,
                            Celular = "3175678901",
                            Correo = "NissanCOl@hotmail.com",
                            Nombre = "Nissan"
                        },
                        new
                        {
                            Id = 22,
                            Celular = "3146789100",
                            Correo = "Tie@gmail.com",
                            Nombre = "TierraGro"
                        },
                        new
                        {
                            Id = 23,
                            Celular = "3197890123",
                            Correo = "RingoCo@hotmail.com",
                            Nombre = "Ringo"
                        },
                        new
                        {
                            Id = 24,
                            Celular = "3108901234",
                            Correo = "Musicalyamaha@gmail.com",
                            Nombre = "Yamaha Musical"
                        });
                });

            modelBuilder.Entity("Inventarios.Server.Models.Salida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadProductos")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFactura")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalDescuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPagarConDescuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPagarSinDescuento")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.ToTable("Salidas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CantidadProductos = 2,
                            FechaFactura = new DateTime(2024, 11, 18, 6, 14, 0, 0, DateTimeKind.Unspecified),
                            IdCliente = 3,
                            TotalDescuento = 26000m,
                            TotalPagarConDescuento = 274000m,
                            TotalPagarSinDescuento = 300000m
                        },
                        new
                        {
                            Id = 2,
                            CantidadProductos = 1,
                            FechaFactura = new DateTime(2024, 11, 18, 6, 14, 0, 0, DateTimeKind.Unspecified),
                            IdCliente = 1,
                            TotalDescuento = 190000m,
                            TotalPagarConDescuento = 3610000m,
                            TotalPagarSinDescuento = 3800000m
                        },
                        new
                        {
                            Id = 3,
                            CantidadProductos = 2,
                            FechaFactura = new DateTime(2024, 11, 18, 6, 14, 0, 0, DateTimeKind.Unspecified),
                            IdCliente = 2,
                            TotalDescuento = 7040m,
                            TotalPagarConDescuento = 164960m,
                            TotalPagarSinDescuento = 172000m
                        });
                });

            modelBuilder.Entity("Inventarios.Server.Models.Entrada", b =>
                {
                    b.HasOne("Inventario.Server.Models.Categoria", "Categoria")
                        .WithMany("Compras")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventarios.Server.Models.Producto", "Producto")
                        .WithMany("Compras")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventarios.Server.Models.Proveedor", "Proveedor")
                        .WithMany("Compras")
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Producto");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Inventarios.Server.Models.Producto", b =>
                {
                    b.HasOne("Inventario.Server.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Inventarios.Server.Models.ProductoSalida", b =>
                {
                    b.HasOne("Inventario.Server.Models.Categoria", "Categoria")
                        .WithMany("ProductoSalidas")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventarios.Server.Models.Entrada", "Entrada")
                        .WithMany("ProductoSalidas")
                        .HasForeignKey("IdEntrada")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventarios.Server.Models.Producto", "Producto")
                        .WithMany("ProductoSalidas")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventarios.Server.Models.Salida", "Salida")
                        .WithMany("ProductoSalidas")
                        .HasForeignKey("IdSalida")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Entrada");

                    b.Navigation("Producto");

                    b.Navigation("Salida");
                });

            modelBuilder.Entity("Inventarios.Server.Models.Salida", b =>
                {
                    b.HasOne("Inventarios.Server.Models.Cliente", "Cliente")
                        .WithMany("Salidas")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Inventario.Server.Models.Categoria", b =>
                {
                    b.Navigation("Compras");

                    b.Navigation("ProductoSalidas");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Inventarios.Server.Models.Cliente", b =>
                {
                    b.Navigation("Salidas");
                });

            modelBuilder.Entity("Inventarios.Server.Models.Entrada", b =>
                {
                    b.Navigation("ProductoSalidas");
                });

            modelBuilder.Entity("Inventarios.Server.Models.Producto", b =>
                {
                    b.Navigation("Compras");

                    b.Navigation("ProductoSalidas");
                });

            modelBuilder.Entity("Inventarios.Server.Models.Proveedor", b =>
                {
                    b.Navigation("Compras");
                });

            modelBuilder.Entity("Inventarios.Server.Models.Salida", b =>
                {
                    b.Navigation("ProductoSalidas");
                });
#pragma warning restore 612, 618
        }
    }
}
